# Generated by Django 3.2.3 on 2021-06-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('size', models.CharField(default=50, max_length=6)),
                ('gender', models.CharField(default=50, max_length=6)),
            ],
        ),
    ]
