# Generated by Django 3.2.3 on 2021-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='k9',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
