# Generated by Django 3.2.3 on 2021-06-05 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_k9_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_app.k9')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
