# Generated by Django 3.2.3 on 2021-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_k9'),
    ]

    operations = [
        migrations.AddField(
            model_name='k9',
            name='name',
            field=models.CharField(default='champ', max_length=20),
        ),
    ]
