# Generated by Django 3.2.3 on 2021-06-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_userdogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDogs',
            new_name='BreederDogs',
        ),
    ]
