# Generated by Django 3.2.3 on 2021-06-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0004_rename_userdogs_breederdogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreederDogs',
        ),
    ]
