# Generated by Django 3.2.3 on 2021-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0005_delete_breederdogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='k9',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
